Version: 1.0.5 # DO NOT CHANGE THIS!
Webhooks:
  # All of the following accept a DISCORDWEBHOOKURL or false.
  alerts: false
  system: false

Messages:
  # Message shown to all players on a kick
  onkick: §4[MAVORIC] A player has been removed from your game for abusing or hacking. Thanks for reporting them!'
  # Message shown to all players on a ban
  onban: §4[MAVORIC] A player has been removed from your game for abusing or hacking. Thanks for reporting them!'

  TPS:
    # Whether or not to enable TPS check messages
    enabled: yes
    # When should staff be messaged about low tps? put something lower than 0 for never
    warn-below: 17
    # When should violation (Cheat detections) be temporarily disabled
    stop-below: 16
  Alerts:
    # Whether or not to disable alerts
    enabled: yes
    # Format of alert messages
    # {player} - Player alert is for
    # {cheat} - Cheat they violated.
    format: "§c[MAVORIC]: §r§4{player} §7failed test for§c {cheat}§8:"

Autoban:
  # Should autobans be enabled? (IF THIS IS ENABLED, BANWAVES ARE OVERRIDDEN REGARDLESS IF BANWAVES ARE ENABLED!)
  enabled: yes
  # If enabled, you can select type "KICK" or "BAN"
  type: kick
  # After how many violations should a player be banned/kicked? (50-80 is recommended)
  max-violations: 60
  # What should the reason be for a ban? (Note, actual reasons are stored in a database.)
  ban-reason: §c§l{cheat-reason}
  # Increment ban times? (If a player has been banned/kicked, go to level 2) This is not implemeneted yet.
  timebans:
    ban-1: 10d
    ban-2: 30d
    ban-3: 60d
    ban-4: never

Banwaves: 
  # Are banwaves enabled on this server?
  enabled: no
  # Should banwaves be automatically issued after a certain amount of players are on it? If so, put the number here.
  auto-issue: no 
  # After how many violations should a player be added to a wave?
  violations: 53
  # After how many violations should a player be banned if they're in a wave. Put "no" for never.
  max-violations: 200

Alerts:
  # Should mavoric alert staff with the "mavoric.alerts" permission / OP players
  enabled: yes
  # Should staff be allowed to decline and accept alerts?
  command: yes
  # If banwaves are enabled, should a denial of a alert remove them from the wave?
  remove-wave: yes

Suppression:
  # Should mavoric suppression be enabled?
  enabled: yes
  # Should all cheats be suppressed? (Master Override)
  all-cheats: yes

Cheats:
  # list of cheat settings
  AutoClicker:
    disabled: no
    suppress: yes
    reason: HummingBird
  AutoArmor:
    disabled: no
    suppress: yes
    reason: Snake
  Flight:
    disabled: no
    suppress: yes
    reason: Eagle
  HighJump:
    disabled: no
    suppress: yes
    reason: BlueBird
  Jesus:
    disabled: no
    suppress: yes
    reason: Strider
  Jetpack:
    disabled: no
    suppress: yes
    reason: BlueJay
  KillAura:
    disabled: no
    suppress: yes
    reason: Lion
  MultiAura:
    disabled: no
    suppress: yes
    reason: Shark
  NoClip:
    disabled: no
    suppress: yes
    reason: WoodPecker
  Reach:
    set-max: no
    disabled: no
    suppress: yes
    reason: Gibbon
  Speed:
    disabled: no
    suppress: yes
    reason: Cheetah
  Teleport:
    disabled: no
    suppress: yes
    reason: Marlin
  

